### ISSUE TITLE
Please add support for llvm-general-pure 3.5.0.0

### ISSUE THREAD

**Issue by peti** [hjwylde/language-qux#7]
We've updated `llvm-general-pure` in NixOS already, and now this package won't compile any more: http://packdeps.haskellers.com/feed?needle=language-qux. It would be great to get an update that remedies this.

**Comment by hjwylde** [comment]
Sure thing. I'll look to get the update into v0.3.

**Comment by hjwylde** [comment]
Looks like I'm having an issue building `llvm-general`, raised an issue on their Github https://github.com/bscarlet/llvm-general/issues/155

**Comment by hjwylde** [comment]
Managed to compile it by installing a different version of gcc and using that instead of OSX's default one.

**Comment by hjwylde** [comment]
See qux-lang/qux#4 for details of the issue.

Removing the milestone in the meantime.
